CXX = g++
CXXFLAGS = -Wall -std=c++11
INCLUDES = -I.
SOURCES = locations.cpp shark.cpp Map.cpp
OBJECTS = $(SOURCES:.cpp=.o)
EXECUTABLE = 


game: 
	$(CXX) $(CXXFLAGS)  -o 


clean:
	rm -f *.o 

run:
	./

test: locations.cpp  Map.cpp shark.cpp test.cpp
	$(CXX) $(CXXFLAGS) locations.cpp  Map.cpp shark.cpp test.cpp -o test

testrun:
	./test